// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vakpzcbwegpdchpltzct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZha3B6Y2J3ZWdwZGNocGx0emN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMjQ5NDQsImV4cCI6MjA3ODYwMDk0NH0.bYGRsP9oujaZLUaS2wNiPIiEGHQeAh2jWrCAy9QwK3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});